# appveyor configuration
version: '{build}'

# Limit history cloned. This matches what travis-CI currently does.
clone_depth: 50

environment:
  matrix:
    - GENERATOR: Visual Studio 12 Win64
      BITS: 64
    - GENERATOR: Visual Studio 12
      BITS: 32
configuration:
  - Debug
  - Release

cache:
  - c:\deps -> appveyor.yml

before_build:
  - cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=ON -DBUILD_TESTS=ON -DRUN_SYSTEM_TESTS=ON -DENABLE_SSL_SUPPORT=True -G"%GENERATOR%" .

build:
  project: ALL_BUILD.vcxproj
  verbosity: normal

artifacts:
  - path: librabbitmq\%CONFIGURATION%
    name: LibRabbit-%BITS%-%CONFIGURATION%.zip
    type: zip
